name: Process and Package Monaspace Fonts

# This action is triggered manually or on push to the main branch
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-font-packages:
    runs-on: ubuntu-latest

    steps:
      # Check out the current repository (where this workflow file resides)
      - name: Checkout workflow repository
        uses: actions/checkout@v4

      # Check out the Monaspace repository into a subdirectory named 'monaspace'
      - name: Checkout Monaspace repository
        uses: actions/checkout@v4
        with:
          repository: githubnext/monaspace
          path: monaspace

      - name: Process and Package Fonts
        # This script now operates from the root of the workspace
        run: |
          # Define the font families to process
          families=("Argon" "Neon" "Xenon" "Radon" "Krypton")
          
          # Process each family
          for family in "${families[@]}"; do
            echo "Processing Monaspace ${family}..."
            
            # Create a dedicated directory for the current font family
            mkdir -p "Monaspace-${family}"
            
            # Copy OTF files from the checked-out monaspace repo
            cp monaspace/fonts/otf/Monaspace${family}-* "Monaspace-${family}/"
            
            # Copy Variable font if it exists
            if [ -f "monaspace/fonts/variable/Monaspace${family}VarVF.ttf" ]; then
                cp "monaspace/fonts/variable/Monaspace${family}VarVF.ttf" "Monaspace-${family}/"
            fi
            
            # Copy Frozen font if it exists
            if [ -f "monaspace/fonts/frozen/Monaspace${family}Frozen.ttf" ]; then
                cp "monaspace/fonts/frozen/Monaspace${family}Frozen.ttf" "Monaspace-${family}/"
            fi
            
            # Copy webfonts, ignoring errors if no files are found
            cp monaspace/fonts/webfonts/Monaspace${family}* "Monaspace-${family}/" 2>/dev/null || true
            
            # Create a zip file for the family
            zip -r "Monaspace-${family}.zip" "Monaspace-${family}"
            
            echo "Successfully created Monaspace-${family}.zip"
          done

      - name: Upload Argon Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Monaspace-Argon
          path: Monaspace-Argon.zip

      - name: Upload Neon Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Monaspace-Neon
          path: Monaspace-Neon.zip

      - name: Upload Xenon Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Monaspace-Xenon
          path: Monaspace-Xenon.zip

      - name: Upload Radon Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Monaspace-Radon
          path: Monaspace-Radon.zip

      - name: Upload Krypton Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Monaspace-Krypton
          path: Monaspace-Krypton.zip
